os:
  - linux
python:
  - "2.7"
  - "3.6"
  - "nightly" 
  - "pypy"

branches:
  only:
    - master


before_install:
  # Show build setup
  - uname -a
  - cat /etc/os-release
  - pwd
  - free -tm
  - python --version
  - git --version
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt


# install dependencies
install:
  - python setup.py install
  - python setup.py test

# run tests
script: 
  - "nosetests --with-coverage --cover-package=quora"

after_failure:
  - bash <(curl -s https://codecov.io/bash)

after_success:
  - bash <(curl -s https://codecov.io/bash)

# email notifications

notifications:
  email:
    recipients:
      - ralic.lo.eng@ieee.org
    on_success: always # default: change
    on_failure: never # default: always